<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerRbbktxf\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerRbbktxf/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerRbbktxf.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerRbbktxf\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerRbbktxf\appProdProjectContainer([
    'container.build_hash' => 'Rbbktxf',
    'container.build_id' => '662135eb',
    'container.build_time' => 1577523652,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerRbbktxf');
